In [1]:
from transformers import pipeline
import torch

# 检查 MPS 是否可用并创建一个简单的任务
device = "mps" if torch.backends.mps.is_available() else "cpu"
print(f"正在使用设备: {device}")

# 运行一个极其微小的模型测试（比如情感分析）
classifier = pipeline("sentiment-analysis", device=device)
result = classifier("I love learning Deep Learning on my Mac!")
print(result)

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


正在使用设备: mps


Device set to use mps


[{'label': 'POSITIVE', 'score': 0.9995256662368774}]


In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import StandardScaler
import numpy as np
import matplotlib.pyplot as plt

torch.manual_seed(42)

# ============================================================
# 1. Generate Data (2 features)
# ============================================================
TRUE_W1 = 300.0   # price per sqft
TRUE_W2 = -5000.0  # price decrease per year
TRUE_B = 50000.0

n_samples = 100
sqft = np.random.randn(n_samples, 1) * 300 + 1500  # 1000-2000 sqft
age = np.random.randn(n_samples, 1) * 5 + 10       # 5-15 years
noise = np.random.randn(n_samples, 1) * 10000

In [5]:
print(sqft[:10])

[[1602.45040336]
 [1561.43435682]
 [1514.4176223 ]
 [1505.27957683]
 [1253.25254495]
 [1826.54881252]
 [ 849.33223713]
 [1451.45148785]
 [1327.10854214]
 [1383.97888156]]


In [6]:
# Combine features
X = np.hstack([sqft, age])  # shape: (100, 2)
y = TRUE_W1 * sqft + TRUE_W2 * age + TRUE_B + noise  # shape: (100, 1)

print(f"X shape: {X.shape}")
print(f"y shape: {y.shape}")
print(f"True params: w1={TRUE_W1}, w2={TRUE_W2}, b={TRUE_B}")


X shape: (100, 2)
y shape: (100, 1)
True params: w1=300.0, w2=-5000.0, b=50000.0


In [7]:
# ============================================================
# 2. Standardize
# ============================================================
X_scaler = StandardScaler()
y_scaler = StandardScaler()

X_norm = X_scaler.fit_transform(X)
y_norm = y_scaler.fit_transform(y)

X_train = torch.tensor(X_norm, dtype=torch.float32)
y_train = torch.tensor(y_norm, dtype=torch.float32)

In [9]:
print(X_norm[:10])

[[ 0.55262227  0.64518703]
 [ 0.39923859 -2.00481283]
 [ 0.22341472 -0.34046773]
 [ 0.18924207 -0.16950212]
 [-0.75323868 -0.69185044]
 [ 1.39066109 -0.78248052]
 [-2.2637398  -2.15062772]
 [-0.01205355  0.07392697]
 [-0.47704666  0.5369604 ]
 [-0.26437423  0.73452388]]


In [11]:
print(X_train[:10])

tensor([[ 0.5526,  0.6452],
        [ 0.3992, -2.0048],
        [ 0.2234, -0.3405],
        [ 0.1892, -0.1695],
        [-0.7532, -0.6919],
        [ 1.3907, -0.7825],
        [-2.2637, -2.1506],
        [-0.0121,  0.0739],
        [-0.4770,  0.5370],
        [-0.2644,  0.7345]])
